[settings.platform.username]
label = "Username"
description = """
The username of the account the token was generated for.

You generally shouldn't have to fill this field as most platforms support fetching
the username from the token the account was generated for.
"""

[settings.platform.token]
label = "Authentication token"
description = """
A token given to you by the platform or a 3rd party service, like a token generator site.
"""

[settings.platform.channel]
label = "Channel"
description = """
The name of the channel to join when the mod finishes connecting to the platform.
"""

[settings.platform.automation.startup.connect]
label = "Auto-connect"
description = """
When enabled, the mod will auto-connect to this platform during startup.
"""

[settings.platform.automation.startup.message]
label = "Startup message"
description = """
When enabled, the mod will send a message to chat when it successfully connects
the the platform.
"""
